### PR TITLE
Cherry-pick r295964 and closely related part of r282387

### PR DESCRIPTION
**Pull request by whitequark**
Fixes https://github.com/rust-lang/rust/issues/41672.

### CODE REVIEW

**Comment by TimNN** [comment]
Is this fix for rust nightly or beta / stable?

If it is for nightly you'll want to use `rust-llvm-2017-04-13` as the base branch, in which case I think that `r282387` should already be included.

**Comment by whitequark** [comment]
> If it is for nightly you'll want to use rust-llvm-2017-04-13 as the base branch, in which case I think that r282387 should already be included.

But yesterday's nightly crashes as described in rust-lang/rust#41672.

**Comment by TimNN** [comment]
> But yesterday's nightly crashes as described in rust-lang/rust#41672.

Note that my statement only refers to `r282387`, not `r295964`.

**Comment by whitequark** [comment]
Updated.

**Comment by alexcrichton** [comment]
@whitequark would it be possible to do a literal `git cherry-pick`? It looks like the commit here was crafted by hand?

**Comment by whitequark** [comment]
@alexcrichton No. There is about a dozen commits between the root branch and the bugfix, all interdependent, and most with significant changes.

**Comment by TimNN** [comment]
> No. There is about a dozen commits between the root branch and the bugfix, all interdependent, and most with significant changes.

@whitequark: Huh? A `git cherry-pick` of llvm-mirror/llvm@93418eeb1d886747332ff404f0e2651e8d77879a causes a minor merge conflict in a test but otherwise applies cleanly for me?

**Comment by whitequark** [comment]
@TimNN Ahhh hm, not sure what went wrong--I must have mixed up something. If you already have the right branch any chance you could simply push it?

**Comment by TimNN** [comment]
Sure.

**Comment by TimNN** [comment]
I've pushed the updated cherry pick.

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
