### PR TITLE
bitrig support

### PR DESCRIPTION
**Pull request by dhuseby**
This adds support for Bitrig at the revision (2d54c4f) currently used by Rust.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I asked this [on the jemalloc PR as well](https://github.com/rust-lang/jemalloc/pull/9#issuecomment-73398624), but have you sent this upstream as well?

**Comment by dhuseby** [comment]
@alexcrichton I'm upstreaming the patch [here](http://reviews.llvm.org/D7543?vs=on&id=19720&whitespace=ignore-all#toc).

**Comment by alexcrichton** [comment]
Thanks! Feel free to ping this PR whenever that gets merged and I'll merge this in.

**Comment by dhuseby** [comment]
@alexcrichton the PR got merged into LLVM: http://reviews.llvm.org/D7543?vs=on&id=19720&whitespace=ignore-all#toc

**Comment by alexcrichton** [comment]
Nice! Do you want to cherry-pick those commits back onto our current branch? I think we're going to try to stay at 3.6 for awhile but we can definitely backport the relevant commits.

**Comment by dhuseby** [comment]
@alexcrichton I'll cherry-pick the change back to this branch and update this PR today.

**Comment by dhuseby** [comment]
@alexcrichton new PR with cherry picked revision is here: https://github.com/rust-lang/llvm/pull/38

**Pull request closed without merging**
