### PR TITLE
Add getPassInfo() function to llvm::Pass

### PR DESCRIPTION
**Pull request by c-a**
When profiling rust compilation I found that llvm spends a lot of time in llvm::PassRegistry::getPassInfo(). To try to fix this I wrote a simple hacky patch for llvm which basically caches the result from llvm::PassRegistry::getPassInfo() in it's corresponding pass. Although hacky it works well in eliminating llvm::PassRegistry::getPassInfo() from my profiles and cuts approximately 50 seconds from a rustc-stage2 build in my testing.

I sent the patch to the llvm list (http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20131223/200046.html) asking for feedback on doing a proper fix but I haven't got any response yet. Anyway since this cuts compilation time quite considerably it may be worthwhile  to include this in the rust fork of llvm for now.

-- Before --
Fraction spent in lvm::PassRegistry::getPassInfo() according to callgrind when compiling sudoku.rs: 14.01

After doing make rustc-stage1
time make -j4 rustc-stage2
real    5m56.428s
user    5m40.291s
sys 0m7.293s

-- After --
Fraction spent in lvm::PassRegistry::getPassInfo() according to callgrind when compiling sudoku.rs:  0.07

After doing make rustc-stage1
time make -j4 rustc-stage2
real    5m16.838s
user    4m55.682s
sys 0m7.536s

### CODE REVIEW

**Comment by alexcrichton** [comment]
Interesting! I'm really liking those improvements in compilation times.

I'm a little hesitant to merge this because we're really starting to diverge from LLVM master, but this is so much of a win I think that may override this. I'm curious what @brson thinks about this?

**Comment by brson** [comment]
Nice win.

Yeah, I'm resigned to taking any patches we need for the time being, so let's merge. It would be super-awesome though if you could get this merged upstream @c-a.

**Comment by alexcrichton** [comment]
I'll merge this and open a PR against mozilla/rust, I'll also rebase on top of the latest LLVM.

Thanks for this!

**Comment by alexcrichton** [comment]
cc https://github.com/mozilla/rust/pull/11853

**Comment by lucab** [comment]
@sylvestre @isanbard can some of the LLVM guys take a look at the above patch sent to the LLVM-commits ML and comment on the mergeability of this one upstream?

**Comment by isanbard** [comment]
On Jan 28, 2014, at 3:04 AM, Luca Bruno notifications@github.com wrote:

> @sylvestre @isanbard can some of the LLVM guys take a look at the above patch sent to the LLVM-commits ML and comments on the mergeability of this upstream?
> 
> I doubt I’d be a good candidate to look at your patch, given that people on the Mozilla LLVM team were so unimpressed by me that they rejected me without even talking to me. Get someone else to do it. You may consider Chandler, who’s reworking all of the pass manager as we speak.

-bw

**Pull request closed without merging**
