### PR TITLE
Skip the ThreadPool unittest to go with the previous commit

### PR DESCRIPTION
**Pull request by tkelman**
In case anyone tries to build the unit tests on this branch

### CODE REVIEW

**Comment by alexcrichton** [comment]
Sure!

**Comment by tkelman** [comment]
Thanks for the patch in 69ef168544e4f15b793dd35d272008fde9a6e835 BTW, it's a little cleaner than what I had in mind. I commented on the upstream bug, but I think with an appropriate cmake probe we could test what the toolchain supports and do this in a way that upstream might merge. [This llvm-dev thread](http://lists.llvm.org/pipermail/llvm-dev/2014-September/077050.html) took a little over a year to manifest as reality, but I don't know if not supporting this configuration is written down as official LLVM policy yet. I think the winpthreads library has been improving on the performance front so it's just a matter of one additional small permissively-licensed dll dependency, and availability of mingw-w64 toolchains compiled with `--enable-threads=posix`.

**Comment by alexcrichton** [comment]
Hm interesting, I was unaware of that thread. If LLVM is basically dropping support for MinGW + win32 threads we may need to rethink which compilers we ourselves are shipping...

**Comment by tkelman** [comment]
Hard to say how many places they will need `std::thread` over time. Eventually libc++ will hopefully provide it, but may take some time for that to really be production usable on windows.

There is https://github.com/meganz/mingw-std-threads, but it doesn't have a very clear license statement and I haven't personally managed to get it to work for this.

And if you cross compile much, both cygwin and opensuse packages for mingw-w64 cross compilers are using win32 threads and may not want to switch or provide two variants (like debian and fedora mingw-cross packages have) in the short term. Moderately annoying.

**Comment by arthurprs** [comment]
I'm not sure why but this was breaking my build. Because the ThreadPool.cpp still gets compiled but it doesn't find the mutex, and friends declarations.

**Pull request merged**
