### PR TITLE
Segmented stack LLVM tests for ARM

### PR DESCRIPTION
**Pull request by neykov**
Add LLVM segmented stack tests for ARM platform.
Update Thumb tests to use generic target.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Awesome, thanks! I'm preparing a patch to submit to LLVM upstream, but these tests are all failing locally for me. I think that it may be because I'm on OSX when perhaps you may be on linux, the errors I'm seeing are that the assembly directives are slightly different and some of the constants are a little off.

Additionally, for the arm tests (not thumb), I'm seeing `Segmented stacks not supported on this platform` which I think is because it's neither linux nor android, so perhaps this should continue to specify linux instead of generic?

**Comment by alexcrichton** [comment]
I have added separate tests for android/linux on all the tests, but the `segmented-stacks-dynamic` on thumb differs significantly for me, does the test pass for you?

**Comment by neykov** [comment]
I double checked and the tests are all successful. I am building it on Linux and it seems to be picking some defaults from the host. Can you try what the results are with the explicit triple.
Can you paste the listing of segmented-stacks-dynamic that you get?

**Comment by alexcrichton** [comment]
Sure, here's the modified tests:
- ARM (passing) - https://gist.github.com/9197234
- ARM dynamic (passing) - https://gist.github.com/9197238
- thumb (passing) - https://gist.github.com/9197244
- thumb dynamic (not passing) - https://gist.github.com/9197249

**Comment by alexcrichton** [comment]
The actual output of `llc  -mtriple=arm-linux-unknown-gnueabi -segmented-stacks -verify-machineinstrs` is  https://gist.github.com/9197267

**Comment by neykov** [comment]
Thanks. For thumb dynamic you have the wrong triple - use thumb instead of arm for the arch.

**Comment by alexcrichton** [comment]
Oh dear, that's embarassing, sorry about that!

**Comment by alexcrichton** [comment]
I have submitted these upstream: http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20140224/205968.html

**Comment by neykov** [comment]
great, crossing fingers :)

**Comment by alexcrichton** [comment]
Upstreamed a few weeks ago, thanks again!

**Pull request closed without merging**
