### PR TITLE
Segmented Stacks support for DragonFly

### PR DESCRIPTION
**Pull request by mneumann**
In the effort of porting Rust to DragonFlyBSD, I noticed that my modified rust compiler (https://github.com/mneumann/rust/tree/dragonfly) fails with <tt>"Segmented stacks not supported on this platform."</tt>. This fixes it.

### CODE REVIEW

**Comment by alexcrichton** [comment]
For core functionality such as this, I prefer to try to upstream these patches first wherever possible. The only current patches that we have on top of upstream LLVM are various optimizations which are not necessary for Rust to operate at full capacity.

Have you attempted to send this a patch upstream first?

**Comment by mneumann** [comment]
I will try to send them upstream.

**Comment by alexcrichton** [comment]
Thanks!

**Comment by alexcrichton** [comment]
If you need help writing tests (if they ask for them), I'm more than willing to help!

**Pull request closed without merging**
