### PR TITLE
Fix assertion in FunctionComparator::cmpInlineAsm

### PR DESCRIPTION
**Pull request by nox**
https://bugs.llvm.org/show_bug.cgi?id=37339

### CODE REVIEW

**Comment by nox** [comment]
Cc @rkruppe @eddyb @nikic

**Comment by hanna-kruppe** [comment]
I'd prefer the commit message (and possibly even a comment in the code) to mention the LLVM bug and that this is a temporary workaround until there is an upstream fix. It's possible that upstream will do the same thing, but if not, we should backport the upstream patch eventually.

**Comment by nox** [comment]
The LLVM bug is mentioned in the commit message.

**Comment by hanna-kruppe** [comment]
Oh, sorry for the noise.

**Comment by nox** [comment]
@eddyb told me to bug you, so here I am @alexcrichton.

**Comment by alexcrichton** [comment]
Thanks! We tend to not accept patches though that aren't in upstream LLVM, so can this be submitted upstream first?

**Comment by nox** [comment]
From what I understood from @rkruppe and @eddyb on IRC they seemed to be ok with landing that until upstream comes up with a patch. This is just the assertion change suggested in the LLVM issue mentioned in the upstream issue.

**Comment by alexcrichton** [comment]
It's effectively our policy at this point that changes like this aren't accepted unless they're in upstream LLVM first, so unless there's extenuating circumstances this should be reviewed by LLVM authors first.

**Comment by nikic** [comment]
I've submitted this change and a test based on @rkruppe's reduced IR for review upstream at https://reviews.llvm.org/D46495.

**Comment by nox** [comment]
@alexcrichton It seems to me that @nikic's patch was accepted upstream, can we backport it here now?

> This revision is now accepted and ready to land.

**Comment by alexcrichton** [comment]
Yes once there's an LLVM commit in the git mirror to cherry-pick then it should be cherry-picked.

**Comment by nikic** [comment]
Change has landed upstream via https://github.com/llvm-mirror/llvm/commit/0ccb7f4a4d99b0381cffc4175f1fc34ddb0085bc, so can be cherry-picked now :)

**Comment by nox** [comment]
I cherry-picked it in this very PR. LGTM?

**Pull request merged**
