### PR TITLE
Stack probe support for x86

### PR DESCRIPTION
**Pull request by Zoxc**
Effort to fix https://github.com/rust-lang/rust/issues/16012

### CODE REVIEW

**Comment by alexcrichton** [comment]
This seems like some pretty serious infrastructure which will break Rust's compatibility with system LLVM versions. Have you attempted to upstream these changes in LLVM yet? Our current fork of LLVM is largely just optimizations which aren't necessary for Rust to work correctly, and we strive to be compatible with system LLVM installations wherever possible.

**Comment by Zoxc** [comment]
There's http://reviews.llvm.org/D4717

**Comment by binarycrusader** [comment]
Should this be closed as abandoned?

**Comment by Zoxc** [comment]
Yeah. See https://github.com/rust-lang/rust/issues/16012 for progress on this

**Pull request closed without merging**
